# Nombre del Workflow
name: 01 - Create Project Issues Manually

# Disparador: workflow_dispatch permite ejecutarlo manualmente
on:
  workflow_dispatch:

jobs:
  create-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r scripts/requirements.txt

      - name: Run issue creation script
        env:
          # Usa el token de GitHub que viene integrado en Actions.
          # Es más seguro que un archivo .env
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Debes configurar REPO_NAME como un "Secret" en tu repositorio
          REPO_NAME: ${{ secrets.REPO_NAME }}
        run: python scripts/github_automation.py
