name: 01 - Create Project Issues Manually

# Disparador: workflow_dispatch permite ejecutarlo manualmente
on:
  workflow_dispatch:

jobs:
  create-issues:
    runs-on: ubuntu-latest
    # Añadir permisos explícitos al job
    permissions:
      contents: read
      issues: write
      pull-requests: write
      organization_administration: read  # Cambiado de 'organization' a 'organization_administration'
      members: read       # Necesario para leer los miembros del equipo
      repository-projects: write
      organization-projects: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r scripts/requirements.txt

      - name: Run issue creation script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
        run: python scripts/github_automation.py